### ISSUE TITLE
Certus quartz ore drops plain quartz

### ISSUE THREAD

**Issue by Cnights** [rgtexa/Automaton#12]
Whenever I mine certus quartz it drops quartz which is ore dicted with nether quartz. Also nether quartz and charged certus quartz drop as block without a silk touch pick. Is this intended or not? Because i see no way to get certus for AE2 currently.  Using version 1.2.0

**Comment by Peter-Pwn** [comment]
Same here.
It's a problem with SimpleOreGeneration. I opened a issue on the mods github page. (https://github.com/Rohzek/SimpleOreGeneration/issues/26)

As a workaround for the certus you can disable the support for AppliedEnergestics 2 in the SimpleOreGeneration config file (set B:supportAppliedEnergestics2 to false in  ...\Automaton\config\simpleoregen\options.cfg). Now you should find AE2 certus ores in new generated chunks.

**Comment by Peter-Pwn** [comment]
All 3 problems get fixed in SimpleOreGeneration 4.3.2.
Because _simpleoregen:surfacecertusquartzore_ have been replaced with the regular ore from AE2 you have to remove 2 lines in ..\Automaton\config\furnus.cfg or it will crash:
`{"inputItem":"simpleoregen:surfacecertusquartzore","outputItem":"appliedenergistics2:material/2#2","experience":0}
 {"inputItem":"simpleoregen:surfacechargedcertusquartzore","outputItem":"appliedenergistics2:material/2#2","experience":0}`


Additionally already generated chunks in the overworld will loose its certus and charged certus ores.
Ore blocks in your inventories will also be deleted.
**New worlds and chunks are not affected!**

**Comment by rgtexa** [comment]
Per above, this is fixed in new version of Simple Ore Generation included in Automaton 1.3.0 released today.
