### ISSUE TITLE
LV Exchanger not triggering quest complete 

### ISSUE THREAD

**Issue by Cnights** [rgtexa/Automaton#3]
I crafted an lv exchanger and it doesn’t complete the quest. Hitting detect/submit doesn’t do anything either.

**Comment by rgtexa** [comment]
Somehow the item required for the quest has an additional NBT tag required that is not present on the crafted item. This should be fixed in the next release.

In the meantime, you can manually complete this quest by doing the following:

1. Enable Edit Mode with /bq_admin edit
2. Open the quest book to the home screen, click Quests, then Edit at the bottom.
3. Select the Quest Line where this quest appears (Powering Up) in the left list and then click Designer.
4. Select the Manual Completion tool (checkmark icon) and then click the quest icon to complete the quest.
5. Click Done until you are back to the main menu, then Exit.
6. Turn off Edit Mode by re-entering /bq_admin edit - this step is very important as quests cannot be completed while in Edit Mode.

**Comment by rgtexa** [comment]
Fixed in 1.1.0 release.
