### ISSUE TITLE
Immersive Engineering GuideBook makes crash the game

### ISSUE THREAD

**Issue by strejdaCharlie** [rgtexa/Automaton#7]
Hello, many times I opened the guidebook and went through a few pages my game completely crashed.

**Comment by rgtexa** [comment]
This is a known [issue](https://github.com/BluSunrize/ImmersiveEngineering/issues/2225) caused by out of date Java being used by the game. Make sure your launcher is using the up-to-date Java version you have installed.

If you are using the Twitch launcher, it uses the bundled Java that comes with Forge, which is an old version. To fix this, you will need to use the Jar Launcher instead of the Native Launcher and ensure it selects the latest Java version. You can do this from the [Twitch Launcher settings for Minecraft](https://i.imgur.com/I9Kva4A.png).

**Comment by strejdaCharlie** [comment]
Thanks a lot. Update of Java solved the issue.
